name: Update Dependencies
on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight
  workflow_dispatch:
    inputs:
      languages:
        description: 'Languages to update (comma-separated)'
        required: false
        default: 'python,node'
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.set-languages.outputs.languages }}
    steps:
      - id: set-languages
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "languages=${{ inputs.languages }}" >> $GITHUB_OUTPUT
          else
            # Default languages for scheduled runs
            echo "languages=python,node" >> $GITHUB_OUTPUT
          fi

  update-dependencies:
    needs: prepare
    strategy:
      matrix:
        language: ${{ fromJson(format('[{0}]', replace(needs.prepare.outputs.languages, ',', '","'))) }}
      fail-fast: false
    uses: ./.github/workflows/update-${{ matrix.language }}-dependencies.yml
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}